export const people = [
    {
        "adult": false,
        "also_known_as": [],
        "biography": "LaNasa was born in New Orleans, Louisiana, the daughter of Anne (née Hardin) and Dr. James J. LaNasa, Jr., a plastic surgeon. LaNasa began dancing at the age of 12, and at the age of 14, she was accepted to the North Carolina School of the Arts in Winston-Salem, North Carolina. After an apprenticeship with Milwaukee Ballet, LaNasa danced with Salt Lake City's Ballet West and the Karole Armitage Ballet.\n\nLaNasa assisted John Carrafa with the choreography for the 1989 film Rooftops. She made her screen debut with a small role in the film Catchfire (1990) and in following years appeared in movies and television. LaNasa played the lead role of Bess Bernstein-Flynn Keats in the NBC comedy series Three Sisters (2001-2002), which was cancelled after two seasons. She was a star of the short-lived CBS series Love Monkey (2006), playing Karen Freed, and HBO's 12 Miles of Bad Road.\n\nLaNasa has appeared in guest roles on numerous television series, including CSI: Crime Scene Investigation, Grey's Anatomy, ER, House M.D., Justice, Two and a Half Men, and Seinfeld. She portrayed recurring character Yvonne Dunbar on Judging Amy, Kim McPherson on The Guardian and Beverly Ford on Big Love. Her film credits include Kiss & Tell (1996), Schizopolis (1996), Alfie (2004), Valentine's Day (2010), Jayne Mansfield's Car (2012), The Campaign (2012) and The Frozen Ground (2012). LaNasa stars in the NBC drama series Deception, which premiered as a mid-season replacement during the 2012–13 television season, as Sophia Bowers. Spouse: Grant Show, (18 August 2012 - present) French Stewart, (19 May 1998 - December 2009) (divorced) Dennis Hopper, (17 June 1989 - April 1992) (divorced) 1 child.",
        "birthday": "1966-12-01",
        "deathday": null,
        "gender": 1,
        "homepage": null,
        "id": 169337,
        "imdb_id": "nm0478762",
        "known_for_department": "Acting",
        "name": "Katherine LaNasa",
        "place_of_birth": "New Orleans, Louisiana, USA",
        "popularity": 371.721,
        "profile_path": "/a1T5Smn7sCEtV8NHvTa5WaxgOML.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "Carrie Frances Fisher ",
            "Кэрри Фишер",
            "Кэрри Фрэнсис Фишер",
            "캐리 피셔"
        ],
        "biography": "Carrie Frances Fisher (21 October 1956 - 27 December 2016) was an American actress, novelist, screenwriter, and lecturer. She is most famous for her portrayal of Princess Leia Organa in the original Star Wars trilogy, her bestselling novel Postcards from the Edge, for which she wrote the screenplay to the film of the same name, and her autobiography Wishful Drinking.",
        "birthday": "1956-10-21",
        "deathday": "2016-12-27",
        "gender": 1,
        "homepage": "https://carriefisher.com/",
        "id": 4,
        "imdb_id": "nm0000402",
        "known_for_department": "Acting",
        "name": "Carrie Fisher",
        "place_of_birth": "Beverly Hills, Los Angeles, California, USA",
        "popularity": 4.891,
        "profile_path": "/rfJtncHewKVnHjqpIZvjn24ESeC.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "Марго Роббі",
            "Марго Робби",
            "มาร์โก ร็อบบี",
            "瑪歌·羅比",
            "마고 로비",
            "مارجوت روبي",
            "マーゴット・ロビー",
            "Марго Роби",
            "Margot Elise Robbie",
            "Μάργκοτ Ελίς Ρόμπι",
            "Μάργκοτ Ρόμπι",
            "玛格特·罗比",
            "Марґо Роббі"
        ],
        "biography": "Margot Elise Robbie (born 2 July 1990) is an Australian actress and producer. She has received nominations for two Academy Awards and five BAFTA Awards. In 2017, Time magazine named her one of the 100 most influential people in the world, and in 2019, she was ranked among the world's highest-paid actresses.\n\nRobbie studied drama at Somerset College and began her career in Australian independent films in the late 2000s, before working in the soap opera Neighbours (2008–2011). After moving to America, she starred in the ABC drama series Pan Am (2011–2012) and had her breakthrough role in Martin Scorsese's black comedy film The Wolf of Wall Street (2013). Robbie's profile continued to grow with starring roles as a grifter in Focus (2015), Jane Porter in The Legend of Tarzan (2016), and Harley Quinn in the DC Extended Universe, beginning with Suicide Squad (2016).\n\nRobbie garnered critical acclaim and nominations for the BAFTA Award and Academy Award for Best Actress for portraying the disgraced figure skater Tonya Harding in the biopic I, Tonya (2017). This acclaim continued for her roles as Queen Elizabeth I in the period drama Mary Queen of Scots (2018), Sharon Tate in the comedy-drama Once Upon a Time in Hollywood (2019), and a fictional Fox News employee in the drama Bombshell (2019). She received BAFTA Award nominations for all three and a nomination for the Academy Award for Best Supporting Actress for the lattermost.\n\nRobbie is married to the filmmaker Tom Ackerley. They are among the founders of the production company LuckyChap Entertainment, under which she has produced some of her own films, as well as the television series Dollface (2019–present).",
        "birthday": "1990-07-02",
        "deathday": null,
        "gender": 1,
        "homepage": null,
        "id": 234352,
        "imdb_id": "nm3053338",
        "known_for_department": "Acting",
        "name": "Margot Robbie",
        "place_of_birth": "Dalby, Queensland, Australia",
        "popularity": 46.628,
        "profile_path": "/euDPyqLnuwaWMHajcU3oZ9uZezR.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "Райан Рейнольдс",
            "رايان رينولدز",
            "라이언 레이놀즈",
            "ライアン・レイノルズ",
            "ไรอัน เรย์โนลส์",
            "萊恩·雷諾斯",
            "Раян Рейнольдс",
            "Ryan Rodney Reynolds",
            "Ράιαν Ρέινολντς",
            "瑞安·雷诺兹",
            "Champ Nightengale"
        ],
        "biography": "Ryan Rodney Reynolds (born 23 October 1976) is a Canadian-American actor, film producer, and entrepreneur. He began his career starring in the Canadian teen soap opera Hillside (1991–1993) and had minor roles before landing the lead role on the sitcom Two Guys and a Girl between 1998 and 2001.\n\nReynolds then starred in a range of films, including Van Wilder (2002), Waiting... (2005), and The Proposal (2009). He also performed in dramatic roles in Buried (2010), Woman in Gold (2015), and Life (2017), starred in action films such as Blade: Trinity (2004), Deadpool (2016), and 6 Underground (2019) and provided voice acting in the animated features The Croods (2013), Turbo (2013), and Pokemon: Detective Pikachu (2019).\n\nReynolds's biggest commercial success came with the superhero films Deadpool (2016) and Deadpool 2 (2018), in which he played the title character. The former set numerous records at the time of its release for an R-rated comedy and his performance earned him nominations at the Critics' Choice Movie Awards and the Golden Globe Awards.\n\nDescription above is from the Wikipedia article Ryan Reynolds, licensed under CC-BY-SA, full list of contributors on Wikipedia.",
        "birthday": "1976-10-23",
        "deathday": null,
        "gender": 2,
        "homepage": null,
        "id": 10859,
        "imdb_id": "nm0005351",
        "known_for_department": "Acting",
        "name": "Ryan Reynolds",
        "place_of_birth": "Vancouver, British Columbia, Canada",
        "popularity": 56.776,
        "profile_path": "/4SYTH5FdB0dAORV98Nwg3llgVnY.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "有村架純",
            "ありむら かすみ",
            "아리무라 카스미"
        ],
        "biography": "Kasumi Arimura (有村 架純 Arimura Kasumi, born February 13, 1993) is a Japanese actress.She is known for playing the young Haruko Amano in Amachan (2013), and the lead role in Strobe Edge (2015) and Flying Colors (2015).\n\nDescription above from the Wikipedia article Kasumi Arimura, licensed under CC-BY-SA, full list of contributors on Wikipedia.",
        "birthday": "1993-02-13",
        "deathday": null,
        "gender": 1,
        "homepage": "http://www.flamme.co.jp/KasumiArimura",
        "id": 1039305,
        "imdb_id": "nm4134328",
        "known_for_department": "Acting",
        "name": "Kasumi Arimura",
        "place_of_birth": "Itami, Hyogo Prefecture, Japan",
        "popularity": 39.301,
        "profile_path": "/irMWWtJQu3kWEOB9JUflKBuhh8H.jpg"
    },
    {
        "adult": false,
        "also_known_as": [],
        "biography": "Daniela Melchior was born on November 1, 1996. She is an actress, known for Parque Mayer (2018), The Suicide Squad (2021) and Massa Fresca (2016).",
        "birthday": "1996-11-01",
        "deathday": null,
        "gender": 1,
        "homepage": null,
        "id": 1784612,
        "imdb_id": "nm6403016",
        "known_for_department": "Acting",
        "name": "Daniela Melchior",
        "place_of_birth": "Lisbon, Portugal",
        "popularity": 25.44,
        "profile_path": "/iLO8qrSldSTC1omutFiO9oyIz6m.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "Alex Daddario",
            "Alexandra Daddorio ",
            "Александра Даддарио",
            "알렉산드라 다드다리오",
            "Alexandra Anna Daddario",
            "Αλεξάντρα Άννα Νταντάριο",
            "Αλεξάντρα Νταντάριο",
            "Александра Даддаріо",
            "ألكسندرا داداريو",
            "അലക്സാണ്ട്ര ദദ്ദാറിയോ",
            "亚历珊德拉·达达里奥"
        ],
        "biography": "Alexandra Anna Daddario is an American actress. She is known for playing Annabeth Chase in the Percy Jackson film series, Blake Gaines in San Andreas (2015), Summer Quinn in Baywatch (2017), Emma Corrigan in Can You Keep a Secret?, and Alexis Butler in We Summon the Darkness (both 2019). She has also starred in the films Texas Chainsaw 3D and Hall Pass and has guest starred in television series such as White Collar, It's Always Sunny in Philadelphia, True Detective, New Girl, and American Horror Story: Hotel.",
        "birthday": "1986-03-16",
        "deathday": null,
        "gender": 1,
        "homepage": null,
        "id": 109513,
        "imdb_id": "nm1275259",
        "known_for_department": "Acting",
        "name": "Alexandra Daddario",
        "place_of_birth": "New York City, New York, USA",
        "popularity": 38.183,
        "profile_path": "/netqGkeTEPtyMBdpMWophvK3y7N.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "Marky Mark",
            "馬克·華伯格",
            "มาร์ก วาห์ลเบิร์ก",
            "Марк Уолберг",
            "マーク・ウォールバーグ",
            "마크 월버그",
            "مارك والبيرغ",
            "马克·沃尔伯格",
            "Mark Robert Michael Wahlberg",
            "Μαρκ Γουόλμπεργκ"
        ],
        "biography": "Mark Robert Michael Wahlberg (born June 5, 1971) is an American actor, producer, restaurateur and former rapper. He is also known by his former stage name Marky Mark from his career with the group Marky Mark and the Funky Bunch, with whom he released the albums Music for the People (1991) and You Gotta Believe (1992).\n\nWahlberg transitioned from music to acting, with his screen debut in Renaissance Man (1994) and his first starring role in Fear (1996). He received critical praise for his performance as porn actor Dirk Diggler in Boogie Nights. In the early 2000s, he ventured into big budget action-oriented movies, such as The Perfect Storm (2000), Planet of the Apes (2001), and The Italian Job (2003). He was nominated for the Academy Award for Best Supporting Actor for playing a police officer in the crime drama The Departed (2006). He was nominated for the Golden Globe Award for Best Actor for the sports drama biopic The Fighter (2010), in which he starred as Micky Ward. In the 2010s, he landed successful comedy roles with The Other Guys (2010), Ted (2012), Ted 2 (2015), Daddy's Home (2015), and Daddy's Home 2 (2017). He also became the protagonist in two films in the Transformers live-action film franchise, Transformers: Age of Extinction and Transformers: The Last Knight. He was the world's highest-paid actor in 2017.\n\nWahlberg also served as executive producer of five HBO series: the comedy-drama Entourage (2004–2011), the period crime drama Boardwalk Empire (2010–2014), the comedy-dramas How to Make It in America (2010–2011) and Ballers (2015–2019), and the documentary McMillions (2020).\n\nDescription above from the Wikipedia article Mark Wahlberg, licensed under CC-BY-SA, full list of contributors on Wikipedia.",
        "birthday": "1971-06-05",
        "deathday": null,
        "gender": 2,
        "homepage": "http://www.markwahlberg.com",
        "id": 13240,
        "imdb_id": "nm0000242",
        "known_for_department": "Acting",
        "name": "Mark Wahlberg",
        "place_of_birth": "Boston, Massachusetts, USA",
        "popularity": 54.446,
        "profile_path": "/bTEFpaWd7A6AZVWOqKKBWzKEUe8.jpg"
    },
    {
        "adult": false,
        "also_known_as": [],
        "biography": "Peter Benson is a Canadian actor, writer and producer for film and television, known for playing Detective Arthur Smith in Hallmark's \"Aurora Teagarden Mystery\" series. He is a graduate of the Vancouver Film School and also has an honors degree in Communications from Carleton University.",
        "birthday": null,
        "deathday": null,
        "gender": 2,
        "homepage": "http://www.marriedtothebossproductions.com/thecompany.html",
        "id": 5009,
        "imdb_id": "nm1193045",
        "known_for_department": "Acting",
        "name": "Peter Benson",
        "place_of_birth": "Canada ",
        "popularity": 24.678,
        "profile_path": "/btcuZXvGZcO1AyCQXcAeWWLf0jI.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "Скарлетт Йоганссон",
            "Скарлетт Йоханссон",
            "스칼릿 조핸슨",
            "سكارليت جوهانسون",
            "史嘉蕾·喬韓森",
            "สการ์เลตต์ โจแฮนส์สัน",
            "スカーレット・ヨハンソン",
            "斯嘉丽·约翰逊",
            "스칼렛 요한슨",
            "Σκάρλετ Τζοχάνσον",
            "اسکارلت جوهانسون"
        ],
        "biography": "Scarlett Johansson, born November 22, 1984, is an American actress, model and singer. She made her film debut in North (1994) and was later nominated for the Independent Spirit Award for Best Female Lead for her performance in Manny & Lo (1996), garnering further acclaim and prominence with roles in The Horse Whisperer (1998) and Ghost World (2001). She shifted to adult roles with her performances in Girl with a Pearl Earring (2003) and Sofia Coppola's Lost in Translation (2003), for which she won a BAFTA award for Best Actress in a Leading Role; both films earned her Golden Globe Award nominations as well.\n\nA role in A Love Song for Bobby Long (2004) earned Johansson her third Golden Globe for Best Actress nomination. Johansson garnered another Golden Globe nomination for Best Supporting Actress with her role in Woody Allen's Match Point (2005). She has played the Marvel comic book character Black Widow/Natasha Romanoff in Iron Man 2 (2010), The Avengers (2012), and Captain America: The Winter Soldier (2014), Avengers: Age of Ultron (2015), Captain America: Civil War (2016), Avengers: Infinity War (2018), Avengers: Endgame (2019), and Black Widow (2020). The 2010 Broadway revival of Arthur Miller's A View From the Bridge won Johansson the Tony Award for Best Performance by a Featured Actress in a Play. As a singer, Johansson has released two albums, Anywhere I Lay My Head and Break Up.\n\nJohansson was nominated for two Academy Awards in 2020 for her work in Marriage Story (2019), and Jojo Rabbit (2019).  Johansson was born in New York City. Her father, Karsten Johansson, is a Danish-born architect, and her paternal grandfather, Ejner Johansson, was a screenwriter and director. Her mother, Melanie Sloan, a producer, comes from an Ashkenazi Jewish family from the Bronx. Johansson has an older sister, Vanessa, who is an actress; an older brother, Adrian; a twin brother, Hunter (who appeared in the film Manny & Lo with Scarlett); and a half-brother, Christian, from her father's re-marriage.",
        "birthday": "1984-11-22",
        "deathday": null,
        "gender": 1,
        "homepage": null,
        "id": 1245,
        "imdb_id": "nm0424060",
        "known_for_department": "Acting",
        "name": "Scarlett Johansson",
        "place_of_birth": "New York City, New York, USA",
        "popularity": 44.587,
        "profile_path": "/6NsMbJXRlDZuDzatN2akFdGuTvx.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "汉黛·埃塞尔"
        ],
        "biography": "Hande Erçel (born 24 November 1993) is a Turkish television actress and model. She is known for her lead role in Aşk Laftan Anlamaz (2016–2017) as Hayat Uzun.",
        "birthday": "1993-11-24",
        "deathday": null,
        "gender": 1,
        "homepage": null,
        "id": 1522703,
        "imdb_id": "nm7495853",
        "known_for_department": "Acting",
        "name": "Hande Erçel",
        "place_of_birth": "Bandirma, Balikesir, Turkey",
        "popularity": 44.015,
        "profile_path": "/heZOn03SAJkwbmTAdk7IXA5yMTV.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "The Rock",
            "Rocky Maivia",
            "The Brahma Bull",
            "The Corporate Champion",
            "Двейн Джонсон",
            "Скеля",
            "Big Bull",
            "드웨인 존슨",
            "Flex Kavana",
            " The Rock 1",
            "Dwayne Douglas Johnson",
            "Ντουέιν Ντάγκλας Τζόνσον",
            "Ντουέιν Τζόνσον",
            "道恩·强森",
            "La Roca",
            "Dwayne ‘The Rock’ Johnson",
            "دوين جونسون",
            "الصخرة",
            "巨石強森",
            "ഡ്വെയ്ൻ ജോൺസൺ",
            "The Peoples Champion",
            "The Great One",
            "Скала"
        ],
        "biography": "An American and Canadian actor, producer and semi-retired professional wrestler, signed with WWE.  Johnson is half-Black and half-Samoan. His father, Rocky Johnson, is a Black Canadian, from Nova Scotia, and part of the first Black tag team champions in WWE history back when it was known as the WWF along with Tony Atlas. His mother is Samoan and the daughter of Peter Maivia, who was also a pro wrestler. Maivia's wife, Lia Maivia, was one of wrestling's few female promoters, taking over Polynesian Pacific Pro Wrestling after her husband's death in 1982, until 1988. Through his mother, he is considered a non-blood relative of the Anoa'i wrestling family. On March 29, 2008, The Rock inducted his father and his grandfather into the WWE Hall of Fame.\n\nAs of 2014, Johnson has a home in Southwest Ranches, Florida as well as Los Angeles, California. He also owns a farm in Virginia. In 2009, Johnson gained citizenship in Canada in honor of his father's background. Though Johnson was previously registered as a Republican, he voted for Barack Obama in the 2008 and 2012 United States presidential elections and is now an independent voter. He stated he did not vote in the 2016 U.S. election.\n\nIn recognition of his service to the Samoan people, and because he is a descendant of Samoan chiefs, Johnson had the noble title of Seiuli bestowed upon him by Malietoa Tanumafili II during his visit there in July 2004. He received a partial Samoan pe'a tattoo on his left side in 2003,and, in 2017, had the small \"Brahma bull\" tattoo on his right arm covered with a larger half-sleeve tattoo of a bull's skull.\n\nJohnson married Dany Garcia on May 3, 1997. Their only child together, a daughter named Simone, was born in August 2001. On June 1, 2007, they announced they were splitting up amicably. Johnson then began dating Lauren Hashian, daughter of Boston drummer Sib Hashian. They first met in 2006 while Johnson was filming The Game Plan. Their first child together, a daughter, was born in December 2015. Their second child, another daughter, was born in April 2018.\n\nJohnson attended the 2000 Democratic National Convention as part of WWE's non-partisan \"Smackdown Your Vote\" campaign, which aimed to influence young people to vote. He also had a speaking role at the 2000 Republican National Convention that same year.\n\nIn 2006, Johnson founded the Dwayne Johnson Rock Foundation, a charity working with at-risk and terminally ill children. On October 2, 2007, he and his ex-wife donated $1 million to the University of Miami to support the renovation of its football facilities; it was noted as the largest donation ever given to the university's athletics department by former students. The University of Miami renamed the Hurricanes' locker room in Johnson's honor. In 2015, Johnson donated $1,500 to a GoFundMe to pay for an abandoned dog's surgery. In 2017, he donated $25,000 to Hurricane Harvey relief efforts. In 2018, Johnson donated a gym to a military base in Oahu, Hawaii. After the 2018 Hawaii floods, he worked with Malama Kauai, a nonprofit organization, to help repair damages caused by the floods.",
        "birthday": "1972-05-02",
        "deathday": null,
        "gender": 2,
        "homepage": "https://www.wwe.com/superstars/the-rock",
        "id": 18918,
        "imdb_id": "nm0425005",
        "known_for_department": "Acting",
        "name": "Dwayne Johnson",
        "place_of_birth": "Hayward, California, USA",
        "popularity": 39.655,
        "profile_path": "/cgoy7t5Ve075naBPcewZrc08qGw.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "Emily Olivia Leah Blunt ",
            "Эмили Блант",
            "إيميلي بلنت",
            "에밀리 블런트",
            "愛蜜莉·布朗",
            "เอมิลี บลันต์",
            "エミリー・ブラント",
            "艾米莉·布朗特",
            "Έμιλι Μπλαντ"
        ],
        "biography": "Emily Olivia Leah Blunt (born 23 February 1983) is a British actress. Her accolades include a Golden Globe Award and a Screen Actors Guild Award, in addition to nominations for two British Academy Film Awards.\n\nEducated at Hurtwood House in Dorking, Blunt made her acting debut in a 2001 stage production of The Royal Family. She went on to appear in the television film Boudica (2003) and portrayed Queen Catherine Howard in the miniseries Henry VIII (2003). She made her feature film debut in the drama My Summer of Love (2004). Blunt's breakthrough came in 2006 with her starring roles in the television film Gideon's Daughter and the comedy-drama film The Devil Wears Prada. The former won her a Golden Globe Award for Best Supporting Actress and the latter earned her a nomination for the BAFTA Award for Best Actress in a Supporting Role.\n\nBlunt's profile continued to grow with leading roles in the period film The Young Victoria (2009), the romantic comedy Salmon Fishing in the Yemen (2011), the science fiction films The Adjustment Bureau (2011), Looper (2012), and Edge of Tomorrow (2014), and the musical films Into the Woods (2014) and Mary Poppins Returns (2018). She received critical acclaim for playing a principled FBI agent in the crime film Sicario (2015), an alcoholic in the thriller The Girl on the Train (2016), which earned her a nomination for the BAFTA Award for Best Actress in a Leading Role, and a survivalist mother in the horror film A Quiet Place (2018). For the latter, which was directed by her husband John Krasinski, she won the Screen Actors Guild Award for Best Supporting Actress.",
        "birthday": "1983-02-23",
        "deathday": null,
        "gender": 1,
        "homepage": null,
        "id": 5081,
        "imdb_id": "nm1289434",
        "known_for_department": "Acting",
        "name": "Emily Blunt",
        "place_of_birth": "Wandsworth, London, England, UK",
        "popularity": 34.56,
        "profile_path": "/jqlqq3knztTnty5rcMg5evqZRCa.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "Kathrin Beckinsale",
            "Кейт Бекінсейл",
            "Кейт Бекинсэйл",
            "케이트 베킨세일",
            "Κέιτ Μπέκινσεϊλ",
            "Κέιτ Μπεκινσέιλ",
            "Kathrin Romary Beckinsale"
        ],
        "biography": "Kathryn Bailey \"Kate\" Beckinsale (born 26 July 1973) is an English actress. Born in Finsbury Park, London, Beckinsale is the daughter of actor Richard Beckinsale, who died from a heart attack in 1979, and actress Judy Loe. She has a paternal half-sister, Samantha, who is also an actress. Her paternal grandfather was half Burmese, and she has said that she was \"very oriental-looking\" as a child.\n\nShe first gained notice, while a student at Oxford University, for making her debut in the film adaptation of Shakespeare's Much Ado About Nothing. Throughout the 1990s, she worked on both film and television, most notably by portraying the title character in the 1996 BBC television series Emma.  In 2001, Beckinsale garnered international recognition when she was cast as the romantic lead opposite Ben Affleck in her breakthrough film, Pearl Harbor (2001). Since then, she has portrayed a variety of characters in projects such as Underworld (2003), The Aviator (2004), and Van Helsing (2004). In 2008, she earned a Critic's Choice Award nomination for her performance in Nothing But the Truth.",
        "birthday": "1973-07-26",
        "deathday": null,
        "gender": 1,
        "homepage": null,
        "id": 3967,
        "imdb_id": "nm0000295",
        "known_for_department": "Acting",
        "name": "Kate Beckinsale",
        "place_of_birth": "Chiswick, London, England, UK",
        "popularity": 30.362,
        "profile_path": "/1mdRhTJGqFwo9Xuul7XO6oXpzhb.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "Mark Sinclair Vincent",
            "Mark Vincent",
            "Він Дізель",
            "Вин Дизель",
            "فان ديزل",
            "วิน ดีเซล",
            "ヴィン・ディーゼル",
            "빈 디젤",
            "馮·迪索",
            "Βιν Ντίζελ",
            "范·迪塞尔",
            "വിൻ ഡീസൽ"
        ],
        "biography": "Mark Sinclair (born 18 July 1967), known professionally as Vin Diesel, is an American actor, producer, director and screenwriter. He is best known for playing Dominic Toretto in the Fast & Furious franchise and is one of the highest-grossing actors of all time.\n\nHe began his career in 1990 but struggled to gain roles until he wrote, directed, produced, scored, and starred in the short film Multi-Facial (1995). This attracted the attention of Steven Spielberg, who was developing Saving Private Ryan (1998); Spielberg re-wrote elements of the film to allow Diesel to appear. He subsequently voiced the titular character in The Iron Giant (1999) while gaining a reputation as an action star after headlining the Fast & Furious, XXX, and The Chronicles of Riddick film franchises.\n\nDiesel voiced Groot in Guardians of the Galaxy (2014) and its sequel (2017), as well as Ralph Breaks the Internet (2018). Away from action films, he has enjoyed commercial success in a number of other genres, such as the comedy film The Pacifier (2005), while his performance in Find Me Guilty (2006) was praised. Diesel portrayed the comic book superhero Bloodshot in its 2020 film adaptation and is slated to appear in the Avatar sequels.\n\nHe founded the production company One Race Films, where he has also served as a producer or executive producer for a number of his star vehicles. Diesel also founded the record label Racetrack Records and video game developer Tigon Studios and has provided his voice and motion capture for all of Tigon's releases.\n\nFrom Wikipedia, the free encyclopedia",
        "birthday": "1967-07-18",
        "deathday": null,
        "gender": 2,
        "homepage": null,
        "id": 12835,
        "imdb_id": "nm0004874",
        "known_for_department": "Acting",
        "name": "Vin Diesel",
        "place_of_birth": "Alameda County, California, USA",
        "popularity": 40.35,
        "profile_path": "/tEoUF0RJqHnskmBOJiDEQhyN7Ok.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "Brittany Valenta",
            "Rachel Tiberman"
        ],
        "biography": "",
        "birthday": null,
        "deathday": null,
        "gender": 1,
        "homepage": null,
        "id": 41953,
        "imdb_id": "nm0204270",
        "known_for_department": "Acting",
        "name": "Brandy Davis",
        "place_of_birth": null,
        "popularity": 14.135,
        "profile_path": null
    },
    {
        "adult": false,
        "also_known_as": [
            "Edward Thomas Hardy",
            "Том Харди",
            "توم هاردي",
            "톰 하디",
            "トム・ハーディ",
            "ทอม ฮาร์ดี",
            "汤姆·哈迪",
            "ტომ ჰარდი",
            "Edward Thomas \"Tom\" Hardy",
            "Έντουαρντ Τόμας \"Τομ\" Χάρντι",
            "Έντουαρντ Τόμας Χάρντι",
            "Τομ Χάρντι",
            "Том Гарді"
        ],
        "biography": "Edward Thomas \"Tom\" Hardy (born 15 September 1977) is an English actor. He is best known for playing the title character in the 2009 British film Bronson, and for his roles in the films Star Trek Nemesis, RocknRolla, and Inception. He has been cast in the Christopher Nolan film The Dark Knight Rises as Bane.",
        "birthday": "1977-09-15",
        "deathday": null,
        "gender": 2,
        "homepage": null,
        "id": 2524,
        "imdb_id": "nm0362766",
        "known_for_department": "Acting",
        "name": "Tom Hardy",
        "place_of_birth": "Hammersmith, London, England, UK",
        "popularity": 24.92,
        "profile_path": "/sGMA6pA2D6X0gun49igJT3piHs3.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "Джейсон Стейтем",
            "Джейсон Стэйтем",
            "جيسون ستاثام",
            "제이슨 스테이섬",
            "ジェイソン・ステイサム",
            "เจสัน สเตธัม",
            "傑森·史塔森",
            "Джейсън Стейтъм",
            "ჯეისონ სტეტჰემი",
            "Τζέισον Στέιθαμ",
            "JS",
            "杰森·斯坦森"
        ],
        "biography": "Jason Statham is an English actor and martial artist, known for his roles in the Guy Ritchie crime films Lock, Stock and Two Smoking Barrels; Revolver; and Snatch. Statham appeared in supporting roles in several American films, such as The Italian Job, as well as playing the lead role in The Transporter, Crank, The Bank Job, War (opposite martial arts star Jet Li), and Death Race. Statham solidified his status as an action hero by appearing alongside established action film actors Sylvester Stallone, Arnold Schwarzenegger, Bruce Willis, Jet Li and Dolph Lundgren in The Expendables. He normally performs his own fight scenes and stunts.",
        "birthday": "1967-07-26",
        "deathday": null,
        "gender": 2,
        "homepage": null,
        "id": 976,
        "imdb_id": "nm0005458",
        "known_for_department": "Acting",
        "name": "Jason Statham",
        "place_of_birth": "Shirebrook, Derbyshire, England, UK",
        "popularity": 38.23,
        "profile_path": "/lldeQ91GwIVff43JBrpdbAAeYWj.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "Wei Zhe Ming",
            "Miles Wei",
            "魏哲鸣",
            "Wei Zhe-Ming",
            "Wei Zheming"
        ],
        "biography": "",
        "birthday": "1990-05-23",
        "deathday": null,
        "gender": 2,
        "homepage": null,
        "id": 1914924,
        "imdb_id": "nm11256195",
        "known_for_department": "Acting",
        "name": "Miles Wei",
        "place_of_birth": "Jinan, Shandong Province, China",
        "popularity": 38.114,
        "profile_path": "/fT4v4LTDXGEFGHe7ZAaRTtqBFYM.jpg"
    },
    {
        "adult": false,
        "also_known_as": [
            "셀마 헤이엑",
            "Σάλμα Χάγιεκ",
            "Са́льма Ха́йек",
            "살마 아예크"
        ],
        "biography": "Salma Hayek Pinault (born Salma Valgarma Hayek Jiménez; September 2, 1966) is a Mexican and American actress and producer. She began her career in Mexico starring in the telenovela Teresa and starred in the film El Callejón de los Milagros (Miracle Alley) for which she was nominated for an Ariel Award. In 1991, Hayek moved to Hollywood and came to prominence with roles in films such as Desperado (1995), From Dusk till Dawn (1996), Wild Wild West, and Dogma (both 1999).\n\nHayek's breakthrough role was in the 2002 film Frida, as Mexican painter Frida Kahlo, for which she was nominated for Best Actress for the Academy Awards, the BAFTA Film Awards, the Golden Globe Awards, and the Screen Actors Guild Awards, and which she also produced. This movie received widespread attention and was a critical and commercial success.\n\nHayek won the Daytime Emmy Award for Outstanding Directing in a Children/Youth/Family Special for The Maldonado Miracle in 2004, and received a Primetime Emmy Award nomination for Outstanding Guest Actress in a Comedy Series after guest-starring in the ABC television comedy-drama Ugly Betty in 2007. She also guest-starred on the NBC comedy series 30 Rock from 2009 to 2013. In 2017, she was nominated for an Independent Spirit Award for her role in Beatriz at Dinner.\n\nHayek's subsequent films include Grown Ups (2010), Puss in Boots (2011), Grown Ups 2 (2013), Tale of Tales (2015), Sausage Party (2016), The Hitman's Bodyguard (2017), Like a Boss (2020) and The Hitman's Wife's Bodyguard (2021).\n\nDescription above from the Wikipedia article Salma Hayek, licensed under CC-BY-SA, full list of contributors on Wikipedia.",
        "birthday": "1966-09-02",
        "deathday": null,
        "gender": 1,
        "homepage": null,
        "id": 3136,
        "imdb_id": "nm0000161",
        "known_for_department": "Acting",
        "name": "Salma Hayek",
        "place_of_birth": "Coatzacoalcos, Veracruz, Mexico",
        "popularity": 13.864,
        "profile_path": "/a1VhN6kvw4tuRrIvGnvAjHAWnD5.jpg"
    }
];